import { PropiedadDetalle } from "../interfaces";

export const descripcionCamposPropiedad = {
  aberturas: "Aberturas",
  acceso: "Acceso",
  activo: "",
  agua_caliente: "Agua caliente",
  agua_corriente: "Agua corriente",
  aire_acondicionado: "Aire acondicionado",
  alambrado_perimetral: "Alambrado Perimetral",
  altura_techo: "Altura de techo",
  ambientes: "Ambientes",
  amueblada: "Amueblada",
  antiguedad: "Antigüedad",
  apto_profesional: "",
  arquitecto: "",
  asfalto: "Asfalto",
  balanza: "Balanza",
  balcones: "Balcones",
  bano_check: "Baño",
  bano_externo_check: "Baño externo",
  bano_servicio_check: "Baño de servicio",
  bano_toilette_check: "Toilette",
  banos_por_genero: "Baños por género",
  banos_servicio: "Baños de servicio",
  banos_texto: "Baños",
  banos: "",
  baulera: "Baulera",
  bebederos: "Bebederos",
  caballerizas: "Caballerizas",
  cable: "Servicio de cable",
  calefaccion: "Calefacción",
  casa_casero: "Casa de casero",
  casa_huespedes: "Casa de huéspedes",
  casa_principal: "Casa principal",
  cerca_ruta: "Cernanía a la ruta",
  chimenea: "Chimenea",
  cochera_tipo: "Tipo de chimenea",
  cochera: "Cochera",
  cocheras: "Cantidad de cocheras",
  cocina_detalles: "NA",
  cocina_muebles: "NA",
  cocina: "Cocina",
  codigo: "Código",
  comedor_diario: "Comedor diario",
  comedor_empleados: "Comedor para empleados",
  demolicion: "Demolición",
  dependencia_servicio: "Dependencia servicios",
  deposito: "Depósito",
  descripcion_corta: "",
  descripcion_larga: "",
  despachos: "Despachos",
  destacado: "",
  direccion_altura: "",
  direccion_exacta: "",
  direccion_publica: "",
  direccion_unidad: "Dirección unidad",
  dormitorio_suite: "Dormitorios en suite",
  dormitorios: "Dormitorios",
  edificio_ascensores: "",
  edificio_estado: "",
  edificio_pisos: "",
  edificio_tipo: "",
  electricidad: "Servicio de electricidad",
  entrada_servicio: "Entrada de servicio",
  entrada_vehiculos: "",
  entrepiso: "",
  escaleras: "",
  escritorio: "Escritorio",
  estado_edificio: "",
  estado_habitacional: "Estado habitacional",
  estado: "Estado",
  estilo: "Estilo",
  exclusiva: "",
  expensas_ano: "Expensas anual",
  expensas_detalles: "Detalle de expensas",
  expensas_incluidas: "Expensas incluidas",
  expensas_mes: "Expensas mensual",
  expensas_monto: "Monto de expensas",
  expensas: "Expensas",
  faja_promocional: "",
  family: "Family",
  financiacion_detalles: "",
  financiacion: "",
  fuerza_motriz: "",
  galeria: "Galería",
  galpones: "Galpones",
  gas: "Gas natural",
  gimnasio: "Gimnasio",
  hall_entrada: "Hall de entrada",
  id_emprendimiento: "",
  id_usuario: "",
  id: "",
  imagen_principal: "",
  inmueble: "",
  internet: "Servicio de internet",
  lagunas: "",
  lavadero: "Lavadero",
  living: "Living",
  local_en: "",
  localidad: "",
  lote_asfalto: "Lote Asfalto", // No
  lote_ubicacion: "",
  lote_vista: "Lote vista",
  lote: "Lote",
  luminosidad: "",
  manga: "Manga",
  mapa_latitud: "",
  mapa_longitud: "",
  maquinas: "",
  molinos: "",
  moneda: "",
  montacargas: "",
  motores: "",
  naves: "",
  obra_sanitaria: "Obra sanitaria",
  of_cocina: "Cocina",
  of_ducha: "Ducha",
  oficinas: "Oficinas",
  operacion: "",
  orden_destacado: "",
  orden: "",
  orientacion: "",
  pais: "",
  pallier: "",
  parrilla: "Parrilla",
  pastura_perenne: "",
  patio: "Patio",
  picadero: "Picadero",
  piscina_calefaccion: "Calefacción en piscina",
  piscina_cerco: "Cerco en piscina",
  piscina_medidas: "Medidas de piscina",
  piscina_tipo: "Tipo de piscina",
  piscina_vista: "Piscina vista",
  piscina: "Piscina",
  piso: "Piso",
  planta_libre: "Planta libre",
  plantas: "Nro. de plantas",
  porche: "Porche",
  porton_medidas: "",
  porton_tipo: "",
  potreros: "",
  precio_publico: "",
  precio: "",
  produccion: "",
  propietario_nota: "",
  puntosDeInteres: "",
  quincho: "Quincho",
  revestimiento: "Revestimientos",
  riego: "Riego",
  rubro_permitido: "",
  sala_reuniones: "",
  seguridad: "Seguridad",
  sembrado: "Sembrado",
  silos: "Silos",
  sol_jardin: "Sol en jardín",
  subbarrio: "",
  subdivisiones: "",
  sucursal: "",
  suelos: "Suelos",
  sum: "S.U.M.",
  sup_balcon: "Sup. Balcón",
  sup_baulera: "",
  sup_cochera: "",
  sup_construible: "",
  sup_contrafrente: "",
  sup_cubierta: "",
  sup_descubierta: "",
  sup_despachos: "",
  sup_edificable: "",
  sup_entrepiso: "",
  sup_fondo: "",
  sup_frente: "",
  sup_hectareas: 'Superficie hectareas',
  sup_lateral_derecho: "",
  sup_lateral_izquierdo: "",
  sup_semi_cubierta: "",
  sup_terreno: "",
  sup_tierras_altas: "",
  sup_tierras_bajas: "",
  sup_total: "",
  techo: "Techo",
  telefono: "",
  terraza: "Terraza",
  tipo_entrada: "",
  tipo_inmueble: "",
  tipo_pisos: "Tipo de piso",
  tipo_zona: "",
  titulo_venta: "",
  toilette: "Toilette",
  unidades_pisos: "",
  vestuarios: "Vestuarios",
  video: "",
  video2: "",
  video3: "",
  vigencia: "",
  visible_web: "",
  vision360: "",
  vivienda_anexa: "Vivienda anexa",
  zona: "",
  zonificacion: "",
} satisfies Record<keyof PropiedadDetalle, string>



// Campos que se convierte 1 por Si
export const camposSiNo:(keyof PropiedadDetalle)[] = [
  'agua_corriente',
  'amueblada',
  'asfalto',
  'balcones',
  'bano_externo_check',
  'bano_servicio_check',
  'bano_toilette_check',
  'baulera',
  'cable',
  'casa_casero',
  'casa_huespedes',
  'chimenea',
  'comedor_diario',
  'dependencia_servicio',
  'deposito',
  'entrada_servicio',
  'escritorio',
  'family', 
  'galeria',
  'hall_entrada',
  'internet', 
  'lavadero',
  'living',
  'parrilla',
  'patio',
  'porche',
  'quincho',
  'riego',
  'sol_jardin',
  'terraza',
]

export const camposPorTipoInmueble = new Map<string, (keyof PropiedadDetalle)[]>();

// Aplica a todos los inmuebles
camposPorTipoInmueble.set('todos', [
  'agua_corriente',
  'estado_habitacional',
  'gas',
  'internet',
  'obra_sanitaria',
  'seguridad',
]);

// Casa
camposPorTipoInmueble.set('casa', [
  'aberturas',
  'aire_acondicionado',
  'ambientes',
  'amueblada',
  'antiguedad',
  'asfalto',
  'balcones',
  'bano_externo_check',
  'bano_servicio_check',
  'bano_toilette_check',
  'banos_texto',
  'baulera',
  'cable',
  'calefaccion',
  'casa_casero',
  'casa_huespedes',
  'chimenea',
  'cochera',
  'cochera_tipo',
  'cocheras',
  'cocina',
  'comedor_diario',
  'dependencia_servicio',
  'deposito',
  'direccion_unidad',
  'dormitorio_suite',
  'dormitorios',
  'entrada_servicio',
  'escritorio',
  'estado',
  'estilo',
  'expensas_ano',
  'expensas_detalles',
  'expensas_mes',
  'family',
  'galeria',
  'hall_entrada',
  'lavadero',
  'living',
  'lote',
  'lote_vista',
  'parrilla',
  'patio',
  'piscina',
  'piscina_calefaccion',
  'piscina_cerco',
  'piscina_medidas',
  'piscina_tipo',
  'piscina_vista',
  'piso',
  'plantas',
  'porche',
  'quincho',
  'revestimiento',
  'riego',
  'sol_jardin',
  'techo',
  'terraza',
  'tipo_pisos',
  'toilette',
]);

// Departamento
// detallesPorTipoDeInmueble.set("departamento", [
//   dormitorios,
//   dormitorio_suite,
//   estado,
//   altura_techo,
//   aberturas,
//   antiguedad,
//   calefaccion,
// ]);



// Oficina
camposPorTipoInmueble.set("oficina", [

]);

// Deposito
camposPorTipoInmueble.set("deposito", [

]);


// Edificio
camposPorTipoInmueble.set("edificio", [
  
]);

// Quinta
camposPorTipoInmueble.set("quinta", [
  
]);



// Quinta
// detallesPorTipoDeInmueble.set("oficina", [
//   estado,
//   aberturas,
//   antiguedad,
//   calefaccion,
//   cocina,
// ]);


// Quinta
// detallesPorTipoDeInmueble.set("quinta", [
//   estado,
//   antiguedad,
//   dormitorios,
//   piscina,
//   zonificacion,
// ]);


