import { PropiedadesResponse } from "../interfaces"


export const propiedadesSeeed: PropiedadesResponse =
   {
      "propiedades": [
         {
            "id": 434074,
            "codigo": "2167",
            "inmueble": "casa",
            "tipo_inmueble": "casa",
            "operacion": "venta",
            "moneda": "dolares",
            "precio": 420000,
            "precio_publico": 1,
            "exclusiva": 0,
            "faja_promocional": "sobre_1260_m2",
            "destacado": 0,
            "titulo_venta": "Excelente Propiedad sobre 1260 m2",
            "zona": "Pilar",
            "localidad": "",
            "sup_total": 299,
            "sup_cubierta": 280,
            "sup_terreno": 1260,
            "plantas": 2,
            "ambientes": 0,
            "dormitorios": 3,
            "dormitorio_suite": 0,
            "banos": 0,
            "cochera": "si",
            "cocheras": 0,
            "imagen_principal": "uploads\/images\/gallery_1755348258_imagen-0.jpg"
         },
         {
            "id": 434072,
            "codigo": "2165",
            "inmueble": "casa",
            "tipo_inmueble": "casa",
            "operacion": "venta",
            "moneda": "dolares",
            "precio": 270000,
            "precio_publico": 1,
            "exclusiva": 0,
            "faja_promocional": "sobre_744_m2",
            "destacado": 0,
            "titulo_venta": "Muy linda propiedad sobre 740 m2",
            "zona": "Pilar",
            "localidad": "",
            "sup_total": 183,
            "sup_cubierta": 153,
            "sup_terreno": 744,
            "plantas": 1,
            "ambientes": 0,
            "dormitorios": 3,
            "dormitorio_suite": 1,
            "banos": 0,
            "cochera": "si",
            "cocheras": 2,
            "imagen_principal": "uploads\/images\/gallery_1748893365_imagen-0.jpg"
         },
         {
            "id": 434071,
            "codigo": "1362",
            "inmueble": "casa",
            "tipo_inmueble": "casa",
            "operacion": "alquiler",
            "moneda": "dolares",
            "precio": 1800,
            "precio_publico": 1,
            "exclusiva": 0,
            "faja_promocional": "sobre_el_golf",
            "destacado": 0,
            "titulo_venta": "Impecable Propiedad Moderna sobre 1700 m2 al Golf",
            "zona": "Pilar",
            "localidad": "country_club",
            "sup_total": 196,
            "sup_cubierta": 189,
            "sup_terreno": 1700,
            "plantas": 2,
            "ambientes": 8,
            "dormitorios": 3,
            "dormitorio_suite": 1,
            "banos": 0,
            "cochera": "si",
            "cocheras": 4,
            "imagen_principal": "uploads\/images\/gallery_1742997941_imagen-0.jpg"
         },
         {
            "id": 434070,
            "codigo": "2164",
            "inmueble": "casa",
            "tipo_inmueble": "casa",
            "operacion": "alquiler",
            "moneda": "dolares",
            "precio": 1700,
            "precio_publico": 1,
            "exclusiva": 0,
            "faja_promocional": "sobre_1300_m2",
            "destacado": 0,
            "titulo_venta": "Propiedad Neoclásica sobre lote de 1300 m2 ",
            "zona": "Pilar",
            "localidad": "country_club",
            "sup_total": 261,
            "sup_cubierta": 220,
            "sup_terreno": 1300,
            "plantas": 2,
            "ambientes": 0,
            "dormitorios": 3,
            "dormitorio_suite": 1,
            "banos": 0,
            "cochera": "si",
            "cocheras": 0,
            "imagen_principal": "uploads\/images\/gallery_1753299809_imagen-0.jpg"
         },
         {
            "id": 434058,
            "codigo": "2157",
            "inmueble": "casa",
            "tipo_inmueble": "casa",
            "operacion": "venta",
            "moneda": "dolares",
            "precio": 399000,
            "precio_publico": 1,
            "exclusiva": 1,
            "faja_promocional": "sobre_1700_m2",
            "destacado": 1,
            "titulo_venta": "Excelente Propiedad Racionalista sobre 1700 m2",
            "zona": "Pilar",
            "localidad": "",
            "sup_total": 430,
            "sup_cubierta": 363,
            "sup_terreno": 1700,
            "plantas": 2,
            "ambientes": 0,
            "dormitorios": 4,
            "dormitorio_suite": 2,
            "banos": 0,
            "cochera": "si",
            "cocheras": 2,
            "imagen_principal": "uploads\/images\/gallery_1746473027_imagen-0.jpg"
         },
         {
            "id": 434057,
            "codigo": "2156",
            "inmueble": "quinta",
            "tipo_inmueble": "casa",
            "operacion": "venta",
            "moneda": "dolares",
            "precio": 435000,
            "precio_publico": 1,
            "exclusiva": 0,
            "faja_promocional": "ruta_8_a_mts_de_chile",
            "destacado": 0,
            "titulo_venta": "Fracción de 3300 m2 sobre Ruta 8 a metros de Calle Chile",
            "zona": "Pilar",
            "localidad": "",
            "sup_total": 0,
            "sup_cubierta": 0,
            "sup_terreno": 3336,
            "plantas": 1,
            "ambientes": 0,
            "dormitorios": 0,
            "dormitorio_suite": 0,
            "banos": 0,
            "cochera": "",
            "cocheras": 0,
            "imagen_principal": "uploads\/images\/gallery_1746041111_imagen-0.jpg"
         },
         {
            "id": 434056,
            "codigo": "2155",
            "inmueble": "departamento",
            "tipo_inmueble": "duplex",
            "operacion": "venta",
            "moneda": "dolares",
            "precio": 128000,
            "precio_publico": 1,
            "exclusiva": 0,
            "faja_promocional": "en_manzanares",
            "destacado": 0,
            "titulo_venta": "Excelente Duplex muy luminoso",
            "zona": "Pilar",
            "localidad": "",
            "sup_total": 101,
            "sup_cubierta": 90,
            "sup_terreno": 0,
            "plantas": 0,
            "ambientes": 3,
            "dormitorios": 2,
            "dormitorio_suite": 0,
            "banos": 2,
            "cochera": "si",
            "cocheras": 0,
            "imagen_principal": "uploads\/images\/gallery_1743693690_imagen-0.jpg"
         },
         {
            "id": 434055,
            "codigo": "2154",
            "inmueble": "casa",
            "tipo_inmueble": "casa",
            "operacion": "venta",
            "moneda": "dolares",
            "precio": 700000,
            "precio_publico": 0,
            "exclusiva": 0,
            "faja_promocional": "con_vista_a_la_laguna",
            "destacado": 1,
            "titulo_venta": "Impecable Casa Moderna con vista a la Laguna",
            "zona": "Pilar",
            "localidad": "",
            "sup_total": 440,
            "sup_cubierta": 400,
            "sup_terreno": 583,
            "plantas": 2,
            "ambientes": 0,
            "dormitorios": 3,
            "dormitorio_suite": 1,
            "banos": 0,
            "cochera": "si",
            "cocheras": 0,
            "imagen_principal": "uploads\/images\/gallery_1742566715_imagen-0.jpg"
         },
         {
            "id": 434054,
            "codigo": "2153",
            "inmueble": "casa",
            "tipo_inmueble": "casa",
            "operacion": "venta",
            "moneda": "dolares",
            "precio": 179000,
            "precio_publico": 1,
            "exclusiva": 0,
            "faja_promocional": "",
            "destacado": 0,
            "titulo_venta": "Propiedad para remodelar o reciclar sobre 1 lote",
            "zona": "Pilar",
            "localidad": "",
            "sup_total": 220,
            "sup_cubierta": 200,
            "sup_terreno": 518,
            "plantas": 2,
            "ambientes": 0,
            "dormitorios": 3,
            "dormitorio_suite": 0,
            "banos": 0,
            "cochera": "si",
            "cocheras": 2,
            "imagen_principal": "uploads\/images\/gallery_1741889343_imagen-0.jpg"
         }
      ],
      "paginacion": {
         "pagina_actual": 3,
         "por_pagina": 9,
         "total": 170,
         "total_paginas": 19,
         "tiene_anterior": true,
         "tiene_siguiente": true
      }
   }
